### ISSUE TITLE
"Porting" to Python

### ISSUE THREAD

**Issue by Hornwitser** [samczsun/Skype4J#69]
I'm interested in making a Skype bridge sort of thing with Python, and as far as I'm aware there are not libraries for the Skype web api for Python (there is one for the old desktop api, but it's getting harder and harder to use).  This makes me evaluate the possibilities of writing my own api wrapper for the web api in Python.

For this I have two questions:
- Can I take this code base and use it as a starting point for such a library?  I'm now familiar with how the licensing and rules around that goes, the code itself isn't going to be verbatim copied as Java and Python are quite different.  But it's ideas and solutions to problems certainly will.  Obviously credit will be given.
- Am I free to chose whatever license I want if I do this, or would you prefer I'd stick with the same license?  If I'm free to chose I'd go for the MIT license, as I just want something simple and permissive.

Apart from these two issues, do you have any recommendations, or things I should know before starting out with this?

**Comment by samczsun** [comment]
Hello!

Thanks for your interest in this project.

For 1), you can feel free to do so. I think everything is reasonably laid out in Endpoints.java, and what they do can be found by tracing their usages through the API (most of the heavy lifting is done in the internal package). If you have any question feel free to ask.

As for 2), because you are re-writing the API in Python I doubt much code will be copy/pasted.  You are free to use the results of any research I've done under whichever license you like. However if you do end up copy/pasting code (eg maybe you decided to use a Python to Java bridge) then I would appreciate it if you would follow the Apache 2.0 guidelines for the code that you are using.

Apart from those two things, I would say get used to looking at obfuscated JavaScript. The last time I checked the entire JavaScript file is around 2.5MB, so you'll need a pretty hefty text editor for that. Skype also tends to force CAPTCHAs on you when you're experimenting, so be prepared for that too.

Finally, I would like to ask you if you are OK with my using any new things you've discovered along the way. It would save me time as well and everyone gets the best of both worlds.

**Comment by Hornwitser** [comment]
Thanks for the answers :smile:.

Given that I value collaboration on this, I've decided to use the Apache 2.0 License.  I don't expect anything to be copied between these projects, but who knows what the future will hold.

Shouldn't be to hard to figure that I'm pretty open on sharing solutions, knowledge, and experience building this.  But first, it looks like I've got some works to do.
